name=mongo-sink
topics=ROSMessagesTopic
connector.class=com.mongodb.kafka.connect.MongoSinkConnector
tasks.max=1

# Message types
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false


# Specific global MongoDB Sink Connector configuration
#connection.uri=mongodb://mongo1:27017,mongo2:27017,mongo3:27017

#atlas vector search SSL on
connection.uri=mongodb+srv://root:*******@cluster0.3b4os1l.mongodb.net/admin?ssl=true

database=RealTimeRAG
collection=RealTimeRAG
max.num.retries=1
retries.defer.timeout=5000


## Document manipulation settings
key.projection.type=none
key.projection.list=
value.projection.type=none
value.projection.list=

field.renamer.mapping=[]
field.renamer.regex=[]

document.id.strategy=com.mongodb.kafka.connect.sink.processor.id.strategy.BsonOidStrategy
post.processor.chain=com.mongodb.kafka.connect.sink.processor.DocumentIdAdder


# Write configuration
delete.on.null.values=false
writemodel.strategy=com.mongodb.kafka.connect.sink.writemodel.strategy.ReplaceOneDefaultStrategy

max.batch.size = 0
rate.limiting.timeout=0
rate.limiting.every.n=0

# Change Data Capture handling
change.data.capture.handler=

# Topic override examples for the sourceB topic
topic.override.sourceB.collection=sourceB
topic.override.sourceB.document.id.strategy=com.mongodb.kafka.connect.sink.processor.id.strategy.ProvidedInValueStrategy
